### ISSUE TITLE
Symbol get_current_value is missing in binary

### ISSUE THREAD

**Issue by AndreasGocht** [score-p/scorep_plugin_cxx_wrapper#1]
When compiling a sync_strict plugin using Intel 2016 the get_current_value is missing (not in the binary).

Example:
try to build https://github.com/score-p/scorep_plugin_hdeem with an Intel 2016.2 version of Score-P.

**Comment by bmario** [comment]
Seems to be an issue in Intel compiler 2016, fixed with 2017
