### ISSUE TITLE
Frequent policy does not result in periodic calls

### ISSUE THREAD

**Issue by NanoNabla** [score-p/scorep_plugin_cxx_wrapper#9]
I'm trying to develop a plugin which calls the backend periodically for values. Therefore, I use the following policies: `async, per_host, scorep_clock, frequent, object_id`
I understood the docs in the way, that using `frequent` should set Score-P to call `stop` and `get_all_values` every X ticks .

`get_metric_gather_interval` returns 3 (for debugging only, bigger values result in the same behaviour) which I expect to make Score-P poll the backend quite often.
Nevertheless, `get_metric_gather_interval` is called at initialization but `stop` and `get_all_values` are only called once at the end of the application.
Runtime of the traced application is about 3min and there are a lot of `ENTER` and `LEAVE` events uniformly distributed  in this time.

Thanks,
Sebastian

**Comment by bmario** [comment]
The `frequent` policy sets the [`delta_t`](http://scorepci.pages.jsc.fz-juelich.de/scorep-pipelines/docs/scorep-6.0/html/structSCOREP__Metric__Plugin__Info.html#a44a2ab20307bb9f44c986772df922c6f) of Score-P metric plugins. However, this has a big disclaimer:

>  NOTE: This is only a lower limit for the time between two reads

If plugins need a periodic measurement, the usual way is to set up a measurement thread with the appropriate time interval between two consecutive measurements. See for example the [`x86_energy` plugin](https://github.com/score-p/scorep_plugin_x86_energy/blob/master/src/x86_energy_plugin.cpp).

**Comment by NanoNabla** [comment]
Ok. I thought this disclaimer states `delta_t` is a lower limit even though an approximate time intervall.
I wonder that setting `delta_t` to 3 ticks results in only one call in over 3 minutes. This seems strange to me.

Anyway, I will try to set up a measurement thread.

**Comment by bmario** [comment]
I'm going to close this, feel free to reopen if you need more information.
